# Generated by Django 4.1.7 on 2023-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employer',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
